name: Ensure GitHub Pages configuration

on:
  push:
    branches: [ master, main ]

permissions:
  contents: read
  pages: write

jobs:
  configure-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Pages to use gh-pages branch
        env:
          GITHUB_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Configuring Pages for $GITHUB_REPO to use gh-pages:/"
          curl -sS -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            https://api.github.com/repos/${GITHUB_REPO}/pages \
            -d '{"source":{"branch":"gh-pages","path":"/"}}' | jq || true
