name: Deploy to GitHub Pages

on:
  push:
    branches: [ master, main ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare site directory
        run: |
          # create a clean folder with only the static site files
          mkdir site
          cp -r index.html about.html offers.html contact.html login.html signup.html assets site/ || true
          # include README if you want
          cp -n README.md site/ || true

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
