name: Deploy to GitHub Pages (gh-pages branch)

on:
  push:
    branches: [ master, main ]
  workflow_dispatch: {}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare site directory
        run: |
          mkdir -p site
          cp -r index.html about.html offers.html contact.html login.html signup.html assets site/ || true
          cp -n README.md site/ || true

      - name: Publish to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          # optional: set publish_branch if you want a different branch (default: gh-pages)
          publish_branch: gh-pages
