name: Deploy to GitHub Pages (gh-pages branch)

on:
  push:
    branches: [ master, main ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Runner debug info
        run: |
          echo "--- runner uname ---"
          uname -a || true
          echo "--- rsync version ---"
          rsync --version || true
          echo "--- git version ---"
          git --version || true
          echo "--- df -h ---"
          df -h || true
          echo "--- whoami ---"
          whoami || true

      - name: Prepare site directory
        run: |
          # copy entire repo into site/ excluding Git metadata and the workflow dir
          mkdir -p site
          # use rsync to avoid copying .git and .github; exclude the site dir itself
          rsync -av --exclude='.git' --exclude='.github' --exclude='site' ./ site/ || (
            echo 'rsync failed, fallback to cp'; 
            cp -r index.html about.html offers.html contact.html login.html signup.html assets site/ || true; 
            cp -n README.md site/ || true
          )

      - name: Debug — list site directory
        run: |
          echo "Listing ./site contents before publish"
          ls -la ./site || true
          echo "Print tree (max depth 3)"
          find ./site -maxdepth 3 -type f -print || true
          echo "--- git status in repo (debug) ---"
          git status --porcelain || true
          echo "--- git branch (debug) ---"
          git branch -vv || true

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
