name: Docker Compose CI

# Allow the workflow to be triggered manually from the Actions UI and
# run on pushes or PRs to the two common default branch names (master/main).
on:
  workflow_dispatch: {}
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  compose:
    name: Build and run docker-compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & run docker-compose
        # Runs docker compose on the Actions runner; this is ephemeral and meant for CI checks
        run: |
          docker compose up --build -d

      - name: Smoke-check the site (optional)
        # The runner runs the services but they are only available from the runner itself.
        run: |
          sleep 3
          if command -v curl >/dev/null 2>&1; then
            curl -fsS http://localhost:8080 || echo 'Site not responding on port 8080'
          else
            echo 'curl not installed on runner'
          fi

      - name: Tear down
        if: always()
        run: |
          docker compose down
