name: Publish to gh-pages (branch)

on:
  push:
    branches: [ master, main ]

jobs:
  publish:
    name: Build and publish to gh-pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare site directory
        run: |
          mkdir -p site
          rsync -av --exclude='.git' --exclude='.github' --exclude='site' ./ site/ || (
            echo 'rsync failed, fallback to cp';
            cp -r index.html about.html offers.html contact.html login.html signup.html assets site/ || true;
            cp -n README.md site/ || true
          )

      - name: Publish to gh-pages branch
        env:
          REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          cd site
          git init
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore(pages): publish site from actions (${GITHUB_SHA::7})" || echo 'no changes to commit'
          # push to gh-pages
          git push --force "https://${GH_TOKEN}@github.com/${REPO}.git" master:gh-pages
