name: Disabled - publish-to-gh-pages

on: {}

# This workflow was disabled and replaced with the official Pages 'deploy-pages.yml'
# Kept as a no-op placeholder to avoid accidental duplicate runs. Delete this file
# if you prefer full removal.

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is intentionally disabled."
